# Generated by Django 3.2 on 2021-04-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_information',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.TextField()),
                ('filepath', models.TextField()),
                ('preview', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='doc_embedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeddings', models.BinaryField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.doc_information')),
            ],
        ),
    ]
